config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/" => "homes#top"
    get "customers/:customer_id/orders" => "orders#index", as: "customer_orders"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end


  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    delete '/cart_items/:id' => 'cart_items#delete'
    delete '/cart_items/delete_all' => 'cart_items#delete_all'
    resources :cart_items, only: [:index, :update, :create]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, :name, :address, presence: true
  validates :postal_code, length: {is: 7}, numericality: {only_integer: true}

  def full_address
    "〒" + self.postal_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { only_integer: ture }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items

  validates :customer_id, :address, :name, :shipping_cost,
            :payment_method, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  def shipping_cost
    self.shipping_cost = 800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :item_id, :order_id, :amount, :price, presence: true
  validates :price, :amount, numericality: { only_integer: true }

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.page(params[:page]).per(10)
    @customer = Customer.find(params[:customer_id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
  end

  private
  def orders_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sub_price(sub)
    sub.item.with_tax_price * sub.amount
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

  
end

app/views/admin/customers/edit.html.erb
<h4 class="m-5 w-25 bg-light text-center">
  <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
        <table>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th><%= f.label '氏名' %></th>
            <td><%= f.text_field :last_name %>　　<%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <th><%= f.label 'フリガナ' %></th>
            <td><%= f.text_field :last_name_kana %>　　<%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <th><%= f.label '郵便番号' %></th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th><%= f.label '住所' %></th>
            <td><%= f.text_field :address, size: 50 %></td>
          </tr>
          <tr>
            <th><%= f.label '電話番号' %></th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th><%= f.label 'メールアドレス' %></th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th><%= f.label '会員ステータス', class: "mr-5" %></th>
            <td>
              <%= f.radio_button :is_deleted, false, cheked: true, class: "mb-2" %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit "変更を保存", class: "btn btn-success my-3" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<h4 class="m-5 w-25 bg-light text-center">会員一覧</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
        <tbody>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == false %>
                <p class="text-success font-weight-bold">有効</p>
              <% else %>
                <p class="text-light font-wight-bold">退会</p>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div class="d-flex justify-content-center"><%= paginate(@customers) %></div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h4 class="m-5 w-25 bg-light text-center">
  <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
</h4>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td>
            <%= @customer.last_name %>　<%= @customer.first_name %>
          </td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == false %>
              <p class="text-success font-weight-bold">有効</p>
            <% else %>
              <p class="text-light font-weight-bold">退会</p>
            <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= link_to '編集する', edit_admin_customer_path(@customer), class: 'btn btn-success mr-5 my-2' %>
            <%= link_to '注文履歴一覧を見る', admin_customer_orders_path(@customer), class: 'btn btn-primary' %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>