config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/" => "homes#top"
    get "customers/:customer_id/orders" => "orders#index", as: "customer_orders"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end


  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    delete '/cart_items/:id' => 'cart_items#delete'
    delete '/cart_items/delete_all' => 'cart_items#delete_all'
    resources :cart_items, only: [:index, :update, :create]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, :name, :address, presence: true
  validates :postal_code, length: {is: 7}, numericality: {only_integer: true}

  def full_address
    "〒" + self.postal_code + " " + self.address + " " + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { only_integer: ture }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items

  validates :customer_id, :address, :name, :shipping_cost,
            :payment_method, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  def shipping_cost
    self.shipping_cost = 800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :item_id, :order_id, :amount, :price, presence: true
  validates :price, :amount, numericality: { only_integer: true }

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.page(params[:page]).per(10)
    @customer = Customer.find(params[:customer_id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
  end

  private
  def orders_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sub_price(sub)
    sub.item.with_tax_price * sub.amount
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

  
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<h4 class="m-5 w-25 bg-light text-center">ジャンル編集</h4>
  <%= form_with model: @genre, url: admin_genre_path do |f| %>
    <table>
      <%= f.label 'ジャンル名', class: "mr-5 ml-3" %>
      <%= f.text_field :name, class: "mr-5" %>
      <%= f.submit '変更を保存', class: 'btn btn-success' %>
    </table>
  <% end %>

app/views/admin/genres/index.html.erb
<h4 class="m-5 w-25 bg-light text-center">ジャンル一覧・追加</h4>
  <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <table>
      <%= f.label 'ジャンル名', class: "mr-5 ml-3" %>
      <%= f.text_field :name, :placeholder => "ジャンル名", class: "mr-5" %>
      <%= f.submit '新規登録', class: 'btn btn-success' %>
    </table>
  <% end %>

  <div class="col-lg-4 col-md-6 col-sm-8 my-5">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th class="text-center">ジャンル名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td class="text-left"><%= genre.name %></td>
          <td class="text-right"><%= link_to '編集する', edit_admin_genre_path(genre), class: 'btn btn-success' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h4 class="m-5 w-25 bg-light text-center">商品編集</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
        <table>
          <tr>
            <th><%= f.label '商品画像' %></th>
            <td><%= f.attachment_field :image, class: "mb-2" %></td>
          </tr>
          <tr>
            <th><%= f.label '商品名' %></th>
            <td><%= f.text_field :name, :placeholder => "商品名", size: "40x1", class: "mb-2" %></td>
          </tr>
          <tr valign="top">
            <th><%= f.label '商品説明' %></th>
            <td><%= f.text_area :introduction, :placeholder => "ここに説明文を記述します", size: "40x5", class: "mb-2" %></td>
          </tr>
          <tr>
            <th><%= f.label 'ジャンル' %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, class: "mb-2", :prompt => "-- 選択してください --" %></td>
          </tr>
          <tr>
            <th><%= f.label '税抜価格' %></th>
            <td><%= f.text_field :price, :placeholder => "1000", class: "mb-2" %>円</td>
          </tr>
          <tr>
            <th><%= f.label '販売ステータス', class: "mr-3" %></th>
            <td>
              <%= f.radio_button :is_active, true, cheked: true, class: "mb-2" %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
            </td>
          </tr>
        </table>
        <div class="d-grid gap-2 col-6 mx-auto">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="row">
  <div class="col-sm-8 px-sm-0 offset-sm-1">
    <h4 class="m-5 w-25 bg-light text-center">商品一覧</h4>
  </div>
  <div class="col-sm-1 text-right mr-5 mt-5">
    <h4><%= link_to '+', new_admin_item_path %></h4>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thad>
        <% @items.each do |item| %>
        <tbody>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active == true %>
                <p class="text-success font-weight-bold">販売中</p>
              <% else %>
                <p class="text-danger font-weight-bold">販売停止中</p>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div class="d-flex justify-content-center"><%= paginate(@items) %></div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<h4 class="m-5 w-25 bg-light text-center">商品新規登録</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0">
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <table>
          <tr>
            <th><%= f.label '商品画像' %></th>
            <td><%= f.attachment_field :image, class: "mb-2" %></td>
          </tr>
          <tr>
            <th><%= f.label '商品名' %></th>
            <td><%= f.text_field :name, :placeholder => "商品名", size: "40x1", class: "mb-2" %></td>
          </tr>
          <tr valign="top">
            <th><%= f.label '商品説明' %></th>
            <td><%= f.text_area :introduction, :placeholder => "ここに説明文を記述します", size: "40x5", class: "mb-2" %></td>
          </tr>
          <tr>
            <th><%= f.label 'ジャンル' %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, class: "mb-2", :prompt => "-- 選択してください --" %></td>
          </tr>
          <tr>
            <th><%= f.label '税抜価格' %></th>
            <td><%= f.text_field :price, :placeholder => "1000", class: "mb-2" %>円</td>
          </tr>
          <tr>
            <th><%= f.label '販売ステータス', class: "mr-3" %></th>
            <td>
              <%= f.radio_button :is_active, true, cheked: true, class: "mb-2" %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中" %>
            </td>
          </tr>
        </table>
        <div class="d-grid gap-2 col-6 mx-auto">
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h4 class="m-5 w-25 bg-light text-center">商品詳細</h4>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <div class="img-container">
        <%= attachment_image_tag @item, :image, format: 'jpeg' %>
      </div>
    </div>
    <div class="col-lg">
      <table class="table table-borderless">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>
            税込金額<br>
            (税抜価格)
          </th>
          <td><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active == true %>
              <p class="text-success font-weight-bold">販売中</p>
            <% else %>
              <p class="text-danger font-weight-bold">販売停止中</p>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to '編集する', edit_admin_item_path(@item), class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/index.html.erb
<h4 class="m-5 w-25 bg-light text-center">
  <%= @customer.last_name %><%= @customer.first_name %>さんの注文履歴
</h4>
<div class="container">
  <div class="row">
    <div class="col-sm-10 px-sm-0">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>購入日時</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td><%= link_to order.created_at_jst.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order), class: "underline" %></td>
            <td><%= order.order_items.sum(:amount) %></td>
            <td><%= order.status %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h4 class="m-5 w-25 bg-light text-center">注文履歴詳細</h4>
<div class="container">
  <div class="row">
    <div class="col-lg">
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= @order.customer.last_name %>
            <%= @order.customer.first_name %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            〒<%= @order.postal_code %><%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
            <%= f.select :status, Order.status.keys, class: "status" %>
            <%= f.submit '更新', class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <% @order.order_details.each do |order_detail| %>
        <tbody>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.item.with_tax_price * order_detail.amount).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true do |f| %>
              <%= f.select :making_status, OrderDetail.making_status.keys, class: "making_status" %>
              <%= f.submit "更新", class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    <div class="col-sm-4">
      <table class="table table-borderless" style="width:50%" %>
        <tr>
          <th>商品合計</th>
          <td class="text-right col-xs-5">
            <%= total_price(@order.order_details).to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th>送料</th>
          <td class="text-right col-xs-5">
            <%= @order.shipping_cost %>円
          </td>
        </tr>
        <tr>
          <th>請求金額</th>
          <td class="text-right col-xs-5">
            <%= (total_price(@order.order_details) + @order.shipping_cost).to_s(:delimited) %>円
          </td>
        </tr>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>